# Generated by Django 2.2.10 on 2020-03-22 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalFacilityCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalFacilityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='api.MedicalFacilityCategory')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('ownership', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=300)),
                ('contact_num', models.CharField(blank=True, max_length=500, null=True)),
                ('is_used_for_Corona_response', models.CharField(blank=True, max_length=500, null=True)),
                ('num_of_bed', models.IntegerField(blank=True, default=0, null=True)),
                ('num_of_icu_ward', models.IntegerField(blank=True, default=0, null=True)),
                ('num_of_icu_ventilators', models.IntegerField(blank=True, default=0, null=True)),
                ('num_of_icu_isolation_ward', models.IntegerField(blank=True, default=0, null=True)),
                ('remaining_capacity', models.IntegerField(blank=True, default=0, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('lat', models.FloatField(blank=True, default=0, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Type', to='api.MedicalFacilityType')),
            ],
        ),
    ]
