# Generated by Django 2.2.10 on 2020-03-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalfacility',
            name='long',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
