# Generated by Django 2.2.10 on 2020-03-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_medicalfacility_long'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalfacility',
            old_name='num_of_icu_isolation_ward',
            new_name='num_of_isolation_ward',
        ),
        migrations.RenameField(
            model_name='medicalfacility',
            old_name='num_of_icu_ventilators',
            new_name='num_of_ventilators',
        ),
        migrations.AlterField(
            model_name='medicalfacility',
            name='ownership',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
