# Generated by Django 2.2.10 on 2020-03-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200322_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tested', models.IntegerField(blank=True, default=0, null=True)),
                ('tested_positive', models.IntegerField(blank=True, default=0, null=True)),
                ('tested_negative', models.IntegerField(blank=True, default=0, null=True)),
                ('death', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
