# Generated by Django 2.2.10 on 2020-03-23 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200322_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_id', models.IntegerField(blank=True, default=0, null=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProvinceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_isolation_ward', models.IntegerField(blank=True, default=0, null=True)),
                ('num_of_icu', models.IntegerField(blank=True, default=0, null=True)),
                ('num_of_ventilators', models.IntegerField(blank=True, default=0, null=True)),
                ('num_of_occupied_isolation_ward', models.IntegerField(blank=True, default=0, null=True)),
                ('num_of_occupied_icu', models.IntegerField(blank=True, default=0, null=True)),
                ('num_of_occupied_ventilators', models.IntegerField(blank=True, default=0, null=True)),
                ('total_tested', models.IntegerField(blank=True, default=0, null=True)),
                ('total_confirmed', models.IntegerField(blank=True, default=0, null=True)),
                ('total_recovered', models.IntegerField(blank=True, default=0, null=True)),
                ('total_death', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('province_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Province', to='api.MedicalFacilityType')),
            ],
        ),
    ]
