# Generated by Django 2.2.10 on 2020-03-23 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_province_provincedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='date',
        ),
    ]
