# Generated by Django 2.2.10 on 2020-03-24 08:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200323_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='medicalfacility',
            name='is_used_for_Corona_response',
        ),
        migrations.RemoveField(
            model_name='medicalfacility',
            name='num_of_icu_ward',
        ),
        migrations.RemoveField(
            model_name='medicalfacility',
            name='num_of_isolation_ward',
        ),
        migrations.RemoveField(
            model_name='medicalfacility',
            name='remaining_capacity',
        ),
        migrations.AddField(
            model_name='medicalfacility',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_facility', to='api.MedicalFacilityCategory'),
        ),
        migrations.AddField(
            model_name='medicalfacility',
            name='contact_person',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='medicalfacility',
            name='hlcit_code',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='medicalfacility',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='medicalfacility',
            name='num_of_icu_bed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='medicalfacility',
            name='num_of_isolation_bed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='medicalfacility',
            name='occupied_icu_bed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='medicalfacility',
            name='occupied_isolation_bed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='medicalfacility',
            name='occupied_ventilators',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='medicalfacility',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_facility', to='api.Province'),
        ),
        migrations.AddField(
            model_name='medicalfacility',
            name='total_death',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='medicalfacility',
            name='total_in_isolation',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='medicalfacility',
            name='total_positive',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='medicalfacility',
            name='total_tested',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='medicalfacility',
            name='used_for_corona_response',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='medicalfacility',
            name='ownership',
            field=models.CharField(choices=[('0', 'UNKNOWN'), ('1', 'GOVERNMENT'), ('2', 'PRIVATE')], default='0', max_length=300),
        ),
        migrations.AddField(
            model_name='medicalfacility',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_facility', to='api.District'),
        ),
        migrations.AddField(
            model_name='medicalfacility',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_facility', to='api.Municipality'),
        ),
    ]
