# Generated by Django 2.2.10 on 2020-03-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200324_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provincedata',
            name='date',
        ),
        migrations.RemoveField(
            model_name='provincedata',
            name='num_of_icu',
        ),
        migrations.RemoveField(
            model_name='provincedata',
            name='num_of_isolation_ward',
        ),
        migrations.RemoveField(
            model_name='provincedata',
            name='num_of_occupied_icu',
        ),
        migrations.RemoveField(
            model_name='provincedata',
            name='num_of_occupied_isolation_ward',
        ),
        migrations.RemoveField(
            model_name='provincedata',
            name='num_of_occupied_ventilators',
        ),
        migrations.RemoveField(
            model_name='provincedata',
            name='total_confirmed',
        ),
        migrations.RemoveField(
            model_name='provincedata',
            name='total_recovered',
        ),
        migrations.AddField(
            model_name='provincedata',
            name='num_of_bed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='provincedata',
            name='num_of_icu_bed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='provincedata',
            name='num_of_isolation_bed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='provincedata',
            name='occupied_icu_bed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='provincedata',
            name='occupied_isolation_bed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='provincedata',
            name='occupied_ventilators',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='provincedata',
            name='total_in_isolation',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='provincedata',
            name='total_positive',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
