# Generated by Django 2.2.10 on 2020-03-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_provincedata_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='provincedata',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
