# Generated by Django 2.2.10 on 2020-03-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200325_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalfacility',
            name='ownership',
            field=models.CharField(choices=[('0', 'Unknown'), ('1', 'Government'), ('2', 'Private'), ('3', 'Nepal Army'), ('nan', 'Unknown')], default='0', max_length=300),
        ),
    ]
