# Generated by Django 2.2.10 on 2020-03-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_agegroupdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='agegroupdata',
            name='districtId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agegroupdata',
            name='munid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agegroupdata',
            name='provinceId',
            field=models.IntegerField(default=0),
        ),
    ]
