# Generated by Django 2.2.10 on 2020-03-26 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200326_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userreport',
            name='body_pain',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userreport',
            name='device_id',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='userreport',
            name='diarrahoe',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userreport',
            name='fast_breathe',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userreport',
            name='have_cough',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userreport',
            name='have_fatigue',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userreport',
            name='have_throat_pain',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userreport',
            name='in_self_quarrantine',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userreport',
            name='runny_nose',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userreport',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userreport',
            name='vomit',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report', to=settings.AUTH_USER_MODEL),
        ),
    ]
