# Generated by Django 2.2.10 on 2020-03-26 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_districtdata_munidata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtdata',
            name='province_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district_data', to='api.Province'),
        ),
    ]
