# Generated by Django 2.2.10 on 2020-03-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200326_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='gender',
            field=models.CharField(default='Male', max_length=63),
        ),
    ]
