# Generated by Django 2.2.10 on 2020-03-28 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_userreport_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='api.District'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='api.Municipality'),
        ),
    ]
