# Generated by Django 2.2.10 on 2020-03-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_globaldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtdata',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='munidata',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='provincedata',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
