# Generated by Django 2.2.10 on 2020-03-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20200329_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='has_convid_contact',
            field=models.BooleanField(default=False),
        ),
    ]
