# Generated by Django 2.2.10 on 2020-03-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_userreport_has_travel_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreport',
            name='has_convid_contact',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
