# Generated by Django 2.2.10 on 2020-03-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20200329_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(blank=True, max_length=255, null=True)),
                ('version_name', models.CharField(blank=True, max_length=255, null=True)),
                ('version_code', models.CharField(blank=True, max_length=255, null=True)),
                ('version_info', models.CharField(blank=True, max_length=255, null=True)),
                ('alert', models.CharField(blank=True, max_length=255, null=True)),
                ('alert_link', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
