# Generated by Django 2.2.10 on 2020-03-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20200330_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=63)),
                ('registration_id', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='userlocation',
            name='device_id',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
