# Generated by Django 2.2.10 on 2020-04-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20200331_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreport',
            name='contact_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='lat',
            field=models.FloatField(blank=True, default=27, null=True),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='long',
            field=models.FloatField(blank=True, default=85, null=True),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
