# Generated by Django 2.2.10 on 2020-04-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20200401_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='district_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='municipality_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
