# Generated by Django 2.2.10 on 2020-04-02 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20200402_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipality',
            name='municipality_id',
        ),
    ]
