# Generated by Django 2.2.10 on 2020-04-02 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_municipality_municipality_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipality',
            name='municipality_id',
        ),
    ]
