# Generated by Django 2.2.10 on 2020-04-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_municipality_municipality_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipality',
            name='municipality_id',
        ),
        migrations.AddField(
            model_name='municipality',
            name='mun_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
