# Generated by Django 2.2.10 on 2020-04-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_userreport_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='provincedata',
            name='total_recovered',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
