# Generated by Django 2.2.10 on 2020-04-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_provincedata_total_recovered'),
    ]

    operations = [
        migrations.AddField(
            model_name='provincedata',
            name='total_negative',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='provincedata',
            name='total_samples_collected',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='provincedata',
            name='total_samples_pending',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
