# Generated by Django 2.2.10 on 2020-04-06 10:13

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0047_auto_20200404_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTaskProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('file', models.FileField(blank=True, max_length=755, null=True, upload_to='celeryfiles')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'In Progress'), (2, 'Completed'), (3, 'Failed')], default=0)),
                ('description', models.CharField(blank=True, max_length=755)),
                ('task_type', models.IntegerField(choices=[(0, 'Generate User Report xlsx')], default=0)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('other_fields', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_object', to='contenttypes.ContentType')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
