# Generated by Django 2.2.10 on 2020-04-06 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20200404_0922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userreport',
            options={'ordering': ['-update_date']},
        ),
    ]
