# Generated by Django 2.2.10 on 2020-04-06 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_celerytaskprogress'),
        ('api', '0048_auto_20200406_0919'),
    ]

    operations = [
    ]
