# Generated by Django 2.2.10 on 2020-04-07 04:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_merge_20200406_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_visits', models.IntegerField(blank=True, default=0, null=True)),
                ('app_downloads', models.IntegerField(blank=True, default=0, null=True)),
                ('self_assessments', models.IntegerField(blank=True, default=0, null=True)),
                ('user_reports', models.IntegerField(blank=True, default=0, null=True)),
                ('phone_calls_received', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='provincedata',
            name='in_quarantine',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total no Quarrantine'),
        ),
        migrations.AlterField(
            model_name='celerytaskprogress',
            name='other_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
