# Generated by Django 2.2.10 on 2020-04-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20200409_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtdata',
            name='total_samples_pending',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total No of Pending Cases (Test Pending)'),
        ),
    ]
