# Generated by Django 2.2.10 on 2020-04-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_districtdata_total_samples_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtdata',
            name='in_quarantine',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total no Quarrantine'),
        ),
        migrations.AddField(
            model_name='munidata',
            name='in_quarantine',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total no Quarrantine'),
        ),
    ]
