# Generated by Django 2.2.10 on 2020-04-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalfacility',
            name='has_ambulance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalfacility',
            name='no_ambulance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
